services:
  ray-worker-embedding-1:
    gpus: []
    environment:
      CUDA: "FALSE"
      RAY_WORKER_EMBEDDING_NUM_GPUS: "0"

  ray-worker-reranker-1:
    gpus: []
    environment:
      CUDA: "FALSE"
      RAY_WORKER_RERANKER_NUM_GPUS: "0"

  main:
    gpus: []
    environment:
      CUDA: "FALSE"
      RAY_EMBEDDING_ACTOR_NUM_GPUS: "0"
      RAY_RERANKER_ACTOR_NUM_GPUS: "0"
      RAY_CODE_EMBEDDING_ACTOR_NUM_GPUS: "0"
